# Site settings
title:              Jekyllbase
email:              hej@urre.me
description:        Minimal Jekyll Starter using Basscss and Gulp
twitter_username:   urre
exclude: 			["node_modules", "gulpfile.js", "package.json", "bower_components", "gulp"]
buildtype: 			development
url:				http://localhost:3000
repo: 				https://github.com/urre/jekyllbase
twittercards: 		true 		

# Build settings
markdown: 			redcarpet
paginate:     		3
highlighter: 		rouge
lsi: 				false
excerpt_separator: 	"\n\n"

# Permalinks
relative_permalinks: true